### ISSUE TITLE
Baseline Code

### ISSUE THREAD

**Issue by Zepp3** [UBCDingXin/improved_CcGAN#2]
Hi!

I see that the codes for the experiments are uploaded in this GitHUB, but is the "baseline code", so the general code not specific for any experiment also available?

Kind regards!

**Comment by UBCDingXin** [comment]
Hi Zepp3,
We currently don't have a "general" code and all codes are designed for some specific experiments in our papers. 
However, you can adjust these codes, such as the codes for RC-49 (https://github.com/UBCDingXin/improved_CcGAN/tree/master/RC-49-improved), to fit other regression datasets.

**Comment by Zepp3** [comment]
Hi @UBCDingXin, thanks!
