### ISSUE TITLE
Pretraining AE for UKT imporve experiment

### ISSUE THREAD

**Issue by ZeWang95** [UBCDingXin/improved_CcGAN#4]
Dear authors,

I found this no file and command for pretraining AE under the UTKFace-improved folder. 
However, I believe this file is required in order to perform the evaluation according to the main.py.

May I ask can I just use the pretrainining script and command under the UTKFace folder in order to reproduce the results?

Thanks

**Comment by UBCDingXin** [comment]
Hi ZeWang95, 

You can use the pre-trained AE for UTKFace to do the evaluation. 
https://github.com/UBCDingXin/improved_CcGAN/blob/master/UTKFace/pretrain_AE.py
