### ISSUE TITLE
h5py issue

### ISSUE THREAD

**Issue by ShenMinSM** [UBCDingXin/improved_CcGAN#7]
Hello !
I am a phd student(not cs) studying GAN in China! I'm new to machine learning.
Thank you so much for the great paper and code!
I wonder are there any references to the code of concat method?

**Comment by UBCDingXin** [comment]
Thanks for your interest in our work. cGAN (concat) is our modification of conventional cGANs. We don't have reference for it.

**Comment by ShenMinSM** [comment]
Thank you for you reply and great work again!
I will keep studying your code and learning from your novel method, which is helpful for my research~
