### ISSUE TITLE
Multi regression labels

### ISSUE THREAD

**Issue by ShenMinSM** [UBCDingXin/improved_CcGAN#8]
Thanks for your great work!
Presently, I am researching some related issues, I am very interested in your codes. I am a non-computer grad student who is new to machine learning, and would like to know if your code can handle multi regression label problems, or what should I do if I want use in multi regression label problems?
I will be appreciated for your reply, thank you very much!

**Comment by UBCDingXin** [comment]
Thanks for your interest in our work. Unfortunately, CcGAN is only designed for scalar regression labels, and its current version cannot be applied to multivariate regression labels. We currently don't know how to modify it to fit the multivariate scenario.

**Comment by ShenMinSM** [comment]
> Thanks for your interest in our work. Unfortunately, CcGAN is only designed for scalar regression labels, and its current version cannot be applied to multivariate regression labels. We currently don't know how to modify it to fit the multivariate scenario.

Sorry to keep bothering you. Your work helps me a lot.
I wonder if there is any other way to apply multiple continuous labels to the gan? Or are there any related papers to recommend? 
Thanks very much for your reply!

**Comment by UBCDingXin** [comment]
You may simply concatenate your multivariate regression with the noise (for generator) or a hidden map (for discriminator). Some models for text-to-image generation may be helpful when texts are represented by a continuous vector. The following paper may be helpful: 
Attribute2image: Conditional image generation from visual attributes

**Comment by ShenMinSM** [comment]
> 
I have tried simply concatenate my multivariate regression with the noise (for generator) or a hidden map (for discriminator), but it seemed labels interfere with each other. I will try the models for text-to-image.
Appreciate your help ~
Thank you!

**Comment by UBCDingXin** [comment]
> > 
> 
> I have tried simply concatenate my multivariate regression with the noise (for generator) or a hidden map (for discriminator), but it seemed labels interfere with each other. I will try the models for text-to-image. Appreciate your help ~ Thank you!

You are welcome.

**Comment by feiyang-cai** [comment]
> > 
> 
> I have tried simply concatenate my multivariate regression with the noise (for generator) or a hidden map (for discriminator), but it seemed labels interfere with each other. I will try the models for text-to-image. Appreciate your help ~ Thank you!

Hi @ShenMinSM , I also encountered similar problem that requires to incorporate multi-labels. Did you get any new findings with this problem? It would be greatly appreciated if you could share any of your findings.

Also, thanks to @UBCDingXin for this great work. This method works perfectly for my project.

Thanks,
Feiyang

**Comment by ShenMinSM** [comment]
Hi, I found that maybe using several embeddings works well in my project but I am nor sure this also works in your project.






| |
沈玟
|
|
***@***.***
|


签名由网易邮箱大师定制


On 11/17/2022 00:56，Feiyang ***@***.***> wrote：

I have tried simply concatenate my multivariate regression with the noise (for generator) or a hidden map (for discriminator), but it seemed labels interfere with each other. I will try the models for text-to-image. Appreciate your help ~ Thank you!

Hi @ShenMinSM , I also encountered similar problem that requires to incorporate multi-labels. Did you get any new findings with this problem? It would be greatly appreciated if you could share any of your findings.

Also, thanks to @UBCDingXin for this great work. This method works perfectly for my project.

Thanks,
Feiyang

**Comment by feiyang-cai** [comment]
> Hi, I found that maybe using several embeddings works well in my project but I am nor sure this also works in your project. | | 沈玟 | | ***@***.*** | 签名由网易邮箱大师定制 On 11/17/2022 00:56，Feiyang ***@***.***> wrote： I have tried simply concatenate my multivariate regression with the noise (for generator) or a hidden map (for discriminator), but it seemed labels interfere with each other. I will try the models for text-to-image. Appreciate your help ~ Thank you! Hi @ShenMinSM , I also encountered similar problem that requires to incorporate multi-labels. Did you get any new findings with this problem? It would be greatly appreciated if you could share any of your findings. Also, thanks to @UBCDingXin for this great work. This method works perfectly for my project. Thanks, Feiyang — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Hi Min, really appreciate your reply. Can you explain a little bit more about "several embeddings"? Do you mean training different embeddings for different label variables? How to deal with the multiple embeddings? Concatenate them? 

Thanks,
Feiyang
